enemy_types:
- type: Beast
  names:
  - Wolf
  - Bear
  - Lion
  - Tiger
  - Boar
  base_stats:
    health_range:
    - 32
    - 40
    mana_range:
    - 28
    - 40
    level_range:
    - 2
    - 12
  attacks:
    melee:
    - name: Slash
      damage:
      - 6
      - 9
      mana_cost: 8
      miss_chance: 0.25
      crit_chance: 0.064
    magic:
    - name: Lightning
      damage:
      - 9
      - 15
      mana_cost: 15
      miss_chance: 0.35
      crit_chance: 0.096
- type: Undead
  names:
  - Skeleton
  - Zombie
  - Ghost
  - Wraith
  - Ghoul
  base_stats:
    health_range:
    - 30
    - 44
    mana_range:
    - 24
    - 40
    level_range:
    - 2
    - 6
  attacks:
    melee:
    - name: Slash
      damage:
      - 5
      - 13
      mana_cost: 5
      miss_chance: 0.25
      crit_chance: 0.064
    magic:
    - name: Lightning
      damage:
      - 9
      - 13
      mana_cost: 17
      miss_chance: 0.35
      crit_chance: 0.096
- type: Elemental
  names:
  - Fire Spirit
  - Water Elemental
  - Earth Golem
  - Wind Wisp
  - Lightning Spark
  base_stats:
    health_range:
    - 28
    - 52
    mana_range:
    - 20
    - 38
    level_range:
    - 1
    - 11
  attacks:
    melee:
    - name: Bite
      damage:
      - 5
      - 9
      mana_cost: 10
      miss_chance: 0.25
      crit_chance: 0.064
    magic:
    - name: Ice Shard
      damage:
      - 7
      - 18
      mana_cost: 17
      miss_chance: 0.35
      crit_chance: 0.096
- type: Dragon
  names:
  - Young Dragon
  - Wyvern
  - Drake
  - Wyrm
  - Dragon Lord
  base_stats:
    health_range:
    - 38
    - 60
    mana_range:
    - 32
    - 41
    level_range:
    - 1
    - 14
  attacks:
    melee:
    - name: Claw
      damage:
      - 7
      - 10
      mana_cost: 5
      miss_chance: 0.25
      crit_chance: 0.064
    magic:
    - name: Lightning
      damage:
      - 8
      - 17
      mana_cost: 15
      miss_chance: 0.35
      crit_chance: 0.096
- type: Demon
  names:
  - Imp
  - Hellhound
  - Demon Warrior
  - Succubus
  - Demon Lord
  base_stats:
    health_range:
    - 36
    - 41
    mana_range:
    - 24
    - 64
    level_range:
    - 2
    - 13
  attacks:
    melee:
    - name: Bite
      damage:
      - 5
      - 11
      mana_cost: 5
      miss_chance: 0.25
      crit_chance: 0.064
    magic:
    - name: Fireball
      damage:
      - 9
      - 12
      mana_cost: 15
      miss_chance: 0.35
      crit_chance: 0.096
- type: Insect
  names:
  - Giant Spider
  - Scorpion
  - Mantis
  - Wasp
  - Beetle
  base_stats:
    health_range:
    - 30
    - 57
    mana_range:
    - 30
    - 64
    level_range:
    - 2
    - 15
  attacks:
    melee:
    - name: Strike
      damage:
      - 7
      - 13
      mana_cost: 8
      miss_chance: 0.25
      crit_chance: 0.064
    magic:
    - name: Lightning
      damage:
      - 11
      - 18
      mana_cost: 20
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Reptile
  names:
  - Lizardman
  - Basilisk
  - Hydra
  - Serpent
  - Crocodile
  base_stats:
    health_range:
    - 45
    - 51
    mana_range:
    - 25
    - 48
    level_range:
    - 1
    - 15
  attacks:
    melee:
    - name: Crush
      damage:
      - 9
      - 18
      mana_cost: 6
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Arcane Blast
      damage:
      - 9
      - 15
      mana_cost: 15
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Goblinoid
  names:
  - Goblin
  - Hobgoblin
  - Orc
  - Troll
  - Ogre
  base_stats:
    health_range:
    - 47
    - 80
    mana_range:
    - 28
    - 56
    level_range:
    - 2
    - 8
  attacks:
    melee:
    - name: Claw
      damage:
      - 8
      - 16
      mana_cost: 7
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Ice Shard
      damage:
      - 12
      - 16
      mana_cost: 18
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Construct
  names:
  - Golem
  - Automaton
  - Gargoyle
  - Sentinel
  - War Machine
  base_stats:
    health_range:
    - 38
    - 63
    mana_range:
    - 26
    - 62
    level_range:
    - 1
    - 5
  attacks:
    melee:
    - name: Strike
      damage:
      - 9
      - 11
      mana_cost: 7
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Arcane Blast
      damage:
      - 12
      - 18
      mana_cost: 17
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Aquatic
  names:
  - Merfolk
  - Sea Serpent
  - Kraken Spawn
  - Naga
  - Leviathan
  base_stats:
    health_range:
    - 47
    - 62
    mana_range:
    - 30
    - 65
    level_range:
    - 2
    - 5
  attacks:
    melee:
    - name: Crush
      damage:
      - 9
      - 12
      mana_cost: 7
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Ice Shard
      damage:
      - 12
      - 21
      mana_cost: 18
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Avian
  names:
  - Giant Eagle
  - Harpy
  - Roc
  - Phoenix
  - Thunderbird
  base_stats:
    health_range:
    - 35
    - 52
    mana_range:
    - 29
    - 74
    level_range:
    - 1
    - 6
  attacks:
    melee:
    - name: Strike
      damage:
      - 6
      - 18
      mana_cost: 8
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Lightning
      damage:
      - 9
      - 17
      mana_cost: 16
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Plant
  names:
  - Treant
  - Vine Horror
  - Spore Beast
  - Man-Eater
  - Bloom Terror
  base_stats:
    health_range:
    - 45
    - 71
    mana_range:
    - 29
    - 41
    level_range:
    - 1
    - 10
  attacks:
    melee:
    - name: Claw
      damage:
      - 6
      - 15
      mana_cost: 7
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Arcane Blast
      damage:
      - 11
      - 16
      mana_cost: 16
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Aberration
  names:
  - Beholder
  - Mind Flayer
  - Gibbering Mouther
  - Otyugh
  - Aboleth
  base_stats:
    health_range:
    - 40
    - 56
    mana_range:
    - 30
    - 70
    level_range:
    - 3
    - 15
  attacks:
    melee:
    - name: Bite
      damage:
      - 6
      - 14
      mana_cost: 7
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Lightning
      damage:
      - 9
      - 19
      mana_cost: 20
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Celestial
  names:
  - Angel
  - Archon
  - Solar
  - Deva
  - Planetar
  base_stats:
    health_range:
    - 45
    - 60
    mana_range:
    - 36
    - 80
    level_range:
    - 3
    - 6
  attacks:
    melee:
    - name: Crush
      damage:
      - 6
      - 12
      mana_cost: 5
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Arcane Blast
      damage:
      - 10
      - 15
      mana_cost: 19
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Fey
  names:
  - Pixie
  - Satyr
  - Dryad
  - Nymph
  - Faerie Dragon
  base_stats:
    health_range:
    - 32
    - 49
    mana_range:
    - 39
    - 50
    level_range:
    - 1
    - 13
  attacks:
    melee:
    - name: Slash
      damage:
      - 8
      - 14
      mana_cost: 5
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Lightning
      damage:
      - 10
      - 21
      mana_cost: 20
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Giant
  names:
  - Hill Giant
  - Stone Giant
  - Frost Giant
  - Fire Giant
  - Cloud Giant
  base_stats:
    health_range:
    - 48
    - 61
    mana_range:
    - 28
    - 40
    level_range:
    - 2
    - 6
  attacks:
    melee:
    - name: Strike
      damage:
      - 6
      - 18
      mana_cost: 5
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Ice Shard
      damage:
      - 12
      - 18
      mana_cost: 15
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Humanoid
  names:
  - Bandit
  - Cultist
  - Assassin
  - Warlock
  - Necromancer
  base_stats:
    health_range:
    - 48
    - 66
    mana_range:
    - 34
    - 52
    level_range:
    - 2
    - 14
  attacks:
    melee:
    - name: Claw
      damage:
      - 8
      - 15
      mana_cost: 8
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Dark Bolt
      damage:
      - 11
      - 21
      mana_cost: 18
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Monstrosity
  names:
  - Chimera
  - Manticore
  - Gorgon
  - Minotaur
  - Griffon
  base_stats:
    health_range:
    - 44
    - 56
    mana_range:
    - 33
    - 74
    level_range:
    - 3
    - 7
  attacks:
    melee:
    - name: Bite
      damage:
      - 8
      - 18
      mana_cost: 9
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Dark Bolt
      damage:
      - 9
      - 18
      mana_cost: 16
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Ooze
  names:
  - Slime
  - Gelatinous Cube
  - Black Pudding
  - Gray Ooze
  - Ochre Jelly
  base_stats:
    health_range:
    - 32
    - 79
    mana_range:
    - 38
    - 45
    level_range:
    - 3
    - 9
  attacks:
    melee:
    - name: Slash
      damage:
      - 9
      - 13
      mana_cost: 9
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Dark Bolt
      damage:
      - 9
      - 19
      mana_cost: 16
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Fiend
  names:
  - Devil
  - Balor
  - Pit Fiend
  - Erinyes
  - Bone Devil
  base_stats:
    health_range:
    - 41
    - 57
    mana_range:
    - 24
    - 50
    level_range:
    - 1
    - 10
  attacks:
    melee:
    - name: Strike
      damage:
      - 7
      - 14
      mana_cost: 7
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Ice Shard
      damage:
      - 11
      - 21
      mana_cost: 20
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Underdark
  names:
  - Drow
  - Duergar
  - Deep Gnome
  - Troglodyte
  - Hook Horror
  base_stats:
    health_range:
    - 41
    - 53
    mana_range:
    - 27
    - 58
    level_range:
    - 3
    - 6
  attacks:
    melee:
    - name: Strike
      damage:
      - 9
      - 11
      mana_cost: 6
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Arcane Blast
      damage:
      - 11
      - 15
      mana_cost: 19
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Arctic
  names:
  - Yeti
  - White Wolf
  - Ice Troll
  - Frost Wurm
  - Abominable Snowman
  base_stats:
    health_range:
    - 38
    - 51
    mana_range:
    - 34
    - 65
    level_range:
    - 3
    - 8
  attacks:
    melee:
    - name: Strike
      damage:
      - 6
      - 15
      mana_cost: 10
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Dark Bolt
      damage:
      - 12
      - 19
      mana_cost: 19
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Desert
  names:
  - Sand Worm
  - Mummy
  - Dust Devil
  - Sandling
  - Desert Drake
  base_stats:
    health_range:
    - 40
    - 48
    mana_range:
    - 38
    - 44
    level_range:
    - 3
    - 7
  attacks:
    melee:
    - name: Crush
      damage:
      - 9
      - 12
      mana_cost: 8
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Lightning
      damage:
      - 10
      - 22
      mana_cost: 17
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Swamp
  names:
  - Bog Beast
  - Crocodilian
  - Marsh Troll
  - Swamp Thing
  - Rot Grub
  base_stats:
    health_range:
    - 44
    - 61
    mana_range:
    - 35
    - 68
    level_range:
    - 1
    - 9
  attacks:
    melee:
    - name: Crush
      damage:
      - 6
      - 13
      mana_cost: 9
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Fireball
      damage:
      - 10
      - 22
      mana_cost: 18
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Mountain
  names:
  - Mountain Lion
  - Cave Bear
  - Rock Troll
  - Cliff Racer
  - Storm Giant
  base_stats:
    health_range:
    - 32
    - 80
    mana_range:
    - 26
    - 75
    level_range:
    - 2
    - 12
  attacks:
    melee:
    - name: Claw
      damage:
      - 8
      - 18
      mana_cost: 10
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Dark Bolt
      damage:
      - 10
      - 18
      mana_cost: 20
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Forest
  names:
  - Dire Wolf
  - Owlbear
  - Displacer Beast
  - Forest Drake
  - Green Dragon
  base_stats:
    health_range:
    - 36
    - 72
    mana_range:
    - 31
    - 66
    level_range:
    - 1
    - 8
  attacks:
    melee:
    - name: Bite
      damage:
      - 9
      - 18
      mana_cost: 5
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Lightning
      damage:
      - 10
      - 15
      mana_cost: 18
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Volcanic
  names:
  - Magma Elemental
  - Fire Drake
  - Lava Troll
  - Salamander
  - Efreet
  base_stats:
    health_range:
    - 42
    - 48
    mana_range:
    - 37
    - 41
    level_range:
    - 2
    - 7
  attacks:
    melee:
    - name: Crush
      damage:
      - 6
      - 15
      mana_cost: 6
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Ice Shard
      damage:
      - 9
      - 19
      mana_cost: 19
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Shadow
  names:
  - Shadow Beast
  - Shade
  - Nightwalker
  - Dark One
  - Void Creature
  base_stats:
    health_range:
    - 33
    - 52
    mana_range:
    - 31
    - 61
    level_range:
    - 2
    - 5
  attacks:
    melee:
    - name: Crush
      damage:
      - 8
      - 13
      mana_cost: 10
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Ice Shard
      damage:
      - 9
      - 20
      mana_cost: 18
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Ethereal
  names:
  - Ghost Dragon
  - Phase Spider
  - Ethereal Filcher
  - Nightmare
  - Astral Deva
  base_stats:
    health_range:
    - 47
    - 76
    mana_range:
    - 24
    - 68
    level_range:
    - 1
    - 6
  attacks:
    melee:
    - name: Slash
      damage:
      - 6
      - 14
      mana_cost: 8
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Fireball
      damage:
      - 12
      - 22
      mana_cost: 15
      miss_chance: 0.3125
      crit_chance: 0.12
- type: Planar
  names:
  - Chaos Beast
  - Gith
  - Modron
  - Slaad
  - Titan
  base_stats:
    health_range:
    - 39
    - 66
    mana_range:
    - 31
    - 58
    level_range:
    - 3
    - 10
  attacks:
    melee:
    - name: Bite
      damage:
      - 6
      - 15
      mana_cost: 8
      miss_chance: 0.1875
      crit_chance: 0.08000000000000002
    magic:
    - name: Dark Bolt
      damage:
      - 9
      - 17
      mana_cost: 20
      miss_chance: 0.3125
      crit_chance: 0.12
affixes:
  prefixes:
  - name: Fierce
    stat_multipliers:
      damage: 1.105
      health: 1.0350000000000001
  - name: Tough
    stat_multipliers:
      health: 1.14
      damage: 0.95
  - name: Magical
    stat_multipliers:
      mana: 1.14
      magic_damage: 1.105
  - name: Swift
    stat_multipliers:
      miss_chance: 0.895
      crit_chance: 1.105
  - name: Ancient
    stat_multipliers:
      health: 1.175
      mana: 1.175
      damage: 1.07
  - name: Savage
    stat_multipliers:
      damage: 1.21
      crit_chance: 1.14
  - name: Armored
    stat_multipliers:
      health: 1.105
      defense: 1.175
  - name: Berserker
    stat_multipliers:
      damage: 1.2799999999999998
      health: 0.8
  - name: Cunning
    stat_multipliers:
      crit_chance: 1.21
      miss_chance: 0.93
  - name: Massive
    stat_multipliers:
      health: 1.35
      damage: 1.14
  suffixes:
  - name: of Darkness
    stat_multipliers:
      magic_damage: 1.14
  - name: of the Mountain
    stat_multipliers:
      health: 1.21
  - name: of Rage
    stat_multipliers:
      damage: 1.175
      crit_chance: 1.14
  - name: of Wisdom
    stat_multipliers:
      mana: 1.21
      magic_damage: 1.105
  - name: of Speed
    stat_multipliers:
      miss_chance: 0.8600000000000001
  - name: of Power
    stat_multipliers:
      damage: 1.21
      magic_damage: 1.21
  - name: of Protection
    stat_multipliers:
      health: 1.14
      defense: 1.21
  - name: of Destruction
    stat_multipliers:
      damage: 1.35
  - name: of the Void
    stat_multipliers:
      magic_damage: 1.2799999999999998
      mana: 1.2799999999999998
  - name: of Eternity
    stat_multipliers:
      health: 1.2799999999999998
      mana: 1.2799999999999998
      damage: 1.14
